In [1]:
import requests

url = "https://pokeapi.co/api/v2/pokemon/pikachu"
response = requests.get(url)
data = response.json()

print(data['name'])
print(data['height'])
print(data['weight'])
print(data['abilities'])

pikachu
4
60
[{'is_hidden': False, 'slot': 1, 'ability': {'name': 'static', 'url': 'https://pokeapi.co/api/v2/ability/9/'}}, {'is_hidden': True, 'slot': 3, 'ability': {'name': 'lightning-rod', 'url': 'https://pokeapi.co/api/v2/ability/31/'}}]

In [2]:
import pandas as pd
from pandas import json_normalize

df = json_normalize(data)
df.head()

,id,name,base_experience,height,is_default,order,weight,abilities,past_abilities,forms,...,sprites.back_shiny,sprites.back_female,sprites.front_shiny,sprites.back_default,sprites.front_female,sprites.front_default,sprites.back_shiny_female,sprites.front_shiny_female,cries.latest,cries.legacy
0,25,pikachu,112,4,True,35,60,"[{'is_hidden': False, 'slot': 1, 'ability': {'...","[{'generation': {'name': 'generation-iv', 'url...","[{'name': 'pikachu', 'url': 'https://pokeapi.c...",...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/crie...,https://raw.githubusercontent.com/PokeAPI/crie...

In [3]:
df.columns.tolist()

['id',
 'name',
 'base_experience',
 'height',
 'is_default',
 'order',
 'weight',
 'abilities',
 'past_abilities',
 'forms',
 'game_indices',
 'held_items',
 'location_area_encounters',
 'moves',
 'stats',
 'past_stats',
 'types',
 'past_types',
 'species.name',
 'species.url',
 'sprites.other.home.front_shiny',
 'sprites.other.home.front_female',
 'sprites.other.home.front_default',
 'sprites.other.home.front_shiny_female',
 'sprites.other.showdown.back_shiny',
 'sprites.other.showdown.back_female',
 'sprites.other.showdown.front_shiny',
 'sprites.other.showdown.back_default',
 'sprites.other.showdown.front_female',
 'sprites.other.showdown.front_default',
 'sprites.other.showdown.back_shiny_female',
 'sprites.other.showdown.front_shiny_female',
 'sprites.other.dream_world.front_female',
 'sprites.other.dream_world.front_default',
 'sprites.other.official-artwork.versions.generation-i.red-and-blue.front_default',
 'sprites.other.official-artwork.versions.generation-i.red-and-green.front_default',
 'sprites.other.official-artwork.versions.generation-ii.gold-and-silver.front_default',
 'sprites.other.official-artwork.front_shiny',
 'sprites.other.official-artwork.front_default',
 'sprites.versions.generation-i.yellow.back_gbc',
 'sprites.versions.generation-i.yellow.back_gray',
 'sprites.versions.generation-i.yellow.front_gbc',
 'sprites.versions.generation-i.yellow.front_gray',
 'sprites.versions.generation-i.yellow.back_default',
 'sprites.versions.generation-i.yellow.front_default',
 'sprites.versions.generation-i.yellow.back_transparent',
 'sprites.versions.generation-i.yellow.front_transparent',
 'sprites.versions.generation-i.yellow.back_transparent_gray',
 'sprites.versions.generation-i.yellow.front_transparent_gray',
 'sprites.versions.generation-i.red-blue.back_gray',
 'sprites.versions.generation-i.red-blue.front_gray',
 'sprites.versions.generation-i.red-blue.back_default',
 'sprites.versions.generation-i.red-blue.front_default',
 'sprites.versions.generation-i.red-blue.back_transparent',
 'sprites.versions.generation-i.red-blue.front_transparent',
 'sprites.versions.generation-i.red-blue.back_transparent_gray',
 'sprites.versions.generation-i.red-blue.front_transparent_gray',
 'sprites.versions.generation-i.red-green-japan.back_gray',
 'sprites.versions.generation-i.red-green-japan.front_gray',
 'sprites.versions.generation-i.red-green-japan.back_default',
 'sprites.versions.generation-i.red-green-japan.front_default',
 'sprites.versions.generation-v.icons.animated.front_default',
 'sprites.versions.generation-v.icons.front_default',
 'sprites.versions.generation-v.black-white.animated.back_shiny',
 'sprites.versions.generation-v.black-white.animated.back_female',
 'sprites.versions.generation-v.black-white.animated.front_shiny',
 'sprites.versions.generation-v.black-white.animated.back_default',
 'sprites.versions.generation-v.black-white.animated.front_female',
 'sprites.versions.generation-v.black-white.animated.front_default',
 'sprites.versions.generation-v.black-white.animated.back_shiny_female',
 'sprites.versions.generation-v.black-white.animated.front_shiny_female',
 'sprites.versions.generation-v.black-white.back_shiny',
 'sprites.versions.generation-v.black-white.back_female',
 'sprites.versions.generation-v.black-white.front_shiny',
 'sprites.versions.generation-v.black-white.back_default',
 'sprites.versions.generation-v.black-white.front_female',
 'sprites.versions.generation-v.black-white.front_default',
 'sprites.versions.generation-v.black-white.back_shiny_female',
 'sprites.versions.generation-v.black-white.front_shiny_female',
 'sprites.versions.generation-ii.gold.back_shiny',
 'sprites.versions.generation-ii.gold.front_shiny',
 'sprites.versions.generation-ii.gold.back_default',
 'sprites.versions.generation-ii.gold.front_default',
 'sprites.versions.generation-ii.gold.back_transparent',
 'sprites.versions.generation-ii.gold.front_transparent',
 'sprites.versions.generation-ii.gold.back_shiny_transparent',
 'sprites.versions.generation-ii.gold.front_shiny_transparent',
 'sprites.versions.generation-ii.silver.back_shiny',
 'sprites.versions.generation-ii.silver.front_shiny',
 'sprites.versions.generation-ii.silver.back_default',
 'sprites.versions.generation-ii.silver.front_default',
 'sprites.versions.generation-ii.silver.back_transparent',
 'sprites.versions.generation-ii.silver.front_transparent',
 'sprites.versions.generation-ii.silver.back_shiny_transparent',
 'sprites.versions.generation-ii.silver.front_shiny_transparent',
 'sprites.versions.generation-ii.crystal.animated.front_shiny',
 'sprites.versions.generation-ii.crystal.animated.front_default',
 'sprites.versions.generation-ii.crystal.back_shiny',
 'sprites.versions.generation-ii.crystal.front_shiny',
 'sprites.versions.generation-ii.crystal.back_default',
 'sprites.versions.generation-ii.crystal.front_default',
 'sprites.versions.generation-ii.crystal.back_transparent',
 'sprites.versions.generation-ii.crystal.front_transparent',
 'sprites.versions.generation-ii.crystal.back_shiny_transparent',
 'sprites.versions.generation-ii.crystal.front_shiny_transparent',
 'sprites.versions.generation-iv.icons.front_default',
 'sprites.versions.generation-iv.platinum.animated.front_shiny',
 'sprites.versions.generation-iv.platinum.animated.front_female',
 'sprites.versions.generation-iv.platinum.animated.front_default',
 'sprites.versions.generation-iv.platinum.animated.front_shiny_female',
 'sprites.versions.generation-iv.platinum.back_shiny',
 'sprites.versions.generation-iv.platinum.back_female',
 'sprites.versions.generation-iv.platinum.front_shiny',
 'sprites.versions.generation-iv.platinum.back_default',
 'sprites.versions.generation-iv.platinum.front_female',
 'sprites.versions.generation-iv.platinum.front_default',
 'sprites.versions.generation-iv.platinum.back_shiny_female',
 'sprites.versions.generation-iv.platinum.front_shiny_female',
 'sprites.versions.generation-iv.diamond-pearl.animated.front_shiny',
 'sprites.versions.generation-iv.diamond-pearl.animated.front_female',
 'sprites.versions.generation-iv.diamond-pearl.animated.front_default',
 'sprites.versions.generation-iv.diamond-pearl.animated.front_shiny_female',
 'sprites.versions.generation-iv.diamond-pearl.back_shiny',
 'sprites.versions.generation-iv.diamond-pearl.back_female',
 'sprites.versions.generation-iv.diamond-pearl.front_shiny',
 'sprites.versions.generation-iv.diamond-pearl.back_default',
 'sprites.versions.generation-iv.diamond-pearl.front_female',
 'sprites.versions.generation-iv.diamond-pearl.front_default',
 'sprites.versions.generation-iv.diamond-pearl.back_shiny_female',
 'sprites.versions.generation-iv.diamond-pearl.front_shiny_female',
 'sprites.versions.generation-iv.heartgold-soulsilver.animated.front_shiny',
 'sprites.versions.generation-iv.heartgold-soulsilver.animated.front_female',
 'sprites.versions.generation-iv.heartgold-soulsilver.animated.front_default',
 'sprites.versions.generation-iv.heartgold-soulsilver.animated.front_shiny_female',
 'sprites.versions.generation-iv.heartgold-soulsilver.back_shiny',
 'sprites.versions.generation-iv.heartgold-soulsilver.back_female',
 'sprites.versions.generation-iv.heartgold-soulsilver.front_shiny',
 'sprites.versions.generation-iv.heartgold-soulsilver.back_default',
 'sprites.versions.generation-iv.heartgold-soulsilver.front_female',
 'sprites.versions.generation-iv.heartgold-soulsilver.front_default',
 'sprites.versions.generation-iv.heartgold-soulsilver.back_shiny_female',
 'sprites.versions.generation-iv.heartgold-soulsilver.front_shiny_female',
 'sprites.versions.generation-ix.champions.front_shiny',
 'sprites.versions.generation-ix.champions.front_default',
 'sprites.versions.generation-ix.scarlet-violet.front_female',
 'sprites.versions.generation-ix.scarlet-violet.front_default',
 'sprites.versions.generation-vi.x-y.back_shiny',
 'sprites.versions.generation-vi.x-y.back_female',
 'sprites.versions.generation-vi.x-y.front_shiny',
 'sprites.versions.generation-vi.x-y.back_default',
 'sprites.versions.generation-vi.x-y.front_female',
 'sprites.versions.generation-vi.x-y.front_default',
 'sprites.versions.generation-vi.x-y.back_shiny_female',
 'sprites.versions.generation-vi.x-y.front_shiny_female',
 'sprites.versions.generation-vi.icons.front_female',
 'sprites.versions.generation-vi.icons.front_default',
 'sprites.versions.generation-vi.omegaruby-alphasapphire.back_shiny',
 'sprites.versions.generation-vi.omegaruby-alphasapphire.back_female',
 'sprites.versions.generation-vi.omegaruby-alphasapphire.front_shiny',
 'sprites.versions.generation-vi.omegaruby-alphasapphire.back_default',
 'sprites.versions.generation-vi.omegaruby-alphasapphire.front_female',
 'sprites.versions.generation-vi.omegaruby-alphasapphire.front_default',
 'sprites.versions.generation-vi.omegaruby-alphasapphire.back_shiny_female',
 'sprites.versions.generation-vi.omegaruby-alphasapphire.front_shiny_female',
 'sprites.versions.generation-iii.icons.front_default',
 'sprites.versions.generation-iii.emerald.animated.back_shiny',
 'sprites.versions.generation-iii.emerald.animated.front_shiny',
 'sprites.versions.generation-iii.emerald.animated.back_default',
 'sprites.versions.generation-iii.emerald.animated.front_default',
 'sprites.versions.generation-iii.emerald.back_shiny',
 'sprites.versions.generation-iii.emerald.front_shiny',
 'sprites.versions.generation-iii.emerald.back_default',
 'sprites.versions.generation-iii.emerald.front_default',
 'sprites.versions.generation-iii.ruby-sapphire.back_shiny',
 'sprites.versions.generation-iii.ruby-sapphire.front_shiny',
 'sprites.versions.generation-iii.ruby-sapphire.back_default',
 'sprites.versions.generation-iii.ruby-sapphire.front_default',
 'sprites.versions.generation-iii.firered-leafgreen.back_shiny',
 'sprites.versions.generation-iii.firered-leafgreen.front_shiny',
 'sprites.versions.generation-iii.firered-leafgreen.back_default',
 'sprites.versions.generation-iii.firered-leafgreen.front_default',
 'sprites.versions.generation-vii.icons.front_female',
 'sprites.versions.generation-vii.icons.front_default',
 'sprites.versions.generation-vii.ultra-sun-ultra-moon.back_shiny',
 'sprites.versions.generation-vii.ultra-sun-ultra-moon.back_female',
 'sprites.versions.generation-vii.ultra-sun-ultra-moon.front_shiny',
 'sprites.versions.generation-vii.ultra-sun-ultra-moon.back_default',
 'sprites.versions.generation-vii.ultra-sun-ultra-moon.front_female',
 'sprites.versions.generation-vii.ultra-sun-ultra-moon.front_default',
 'sprites.versions.generation-vii.ultra-sun-ultra-moon.back_shiny_female',
 'sprites.versions.generation-vii.ultra-sun-ultra-moon.front_shiny_female',
 'sprites.versions.generation-vii.lets-go-pikachu-lets-go-eevee.icons.front_default',
 'sprites.versions.generation-vii.lets-go-pikachu-lets-go-eevee.back_shiny',
 'sprites.versions.generation-vii.lets-go-pikachu-lets-go-eevee.back_female',
 'sprites.versions.generation-vii.lets-go-pikachu-lets-go-eevee.front_shiny',
 'sprites.versions.generation-vii.lets-go-pikachu-lets-go-eevee.back_default',
 'sprites.versions.generation-vii.lets-go-pikachu-lets-go-eevee.front_female',
 'sprites.versions.generation-vii.lets-go-pikachu-lets-go-eevee.front_default',
 'sprites.versions.generation-vii.lets-go-pikachu-lets-go-eevee.back_shiny_female',
 'sprites.versions.generation-vii.lets-go-pikachu-lets-go-eevee.front_shiny_female',
 'sprites.versions.generation-viii.icons.front_female',
 'sprites.versions.generation-viii.icons.front_default',
 'sprites.versions.generation-viii.brilliant-diamond-shining-pearl.front_default',
 'sprites.back_shiny',
 'sprites.back_female',
 'sprites.front_shiny',
 'sprites.back_default',
 'sprites.front_female',
 'sprites.front_default',
 'sprites.back_shiny_female',
 'sprites.front_shiny_female',
 'cries.latest',
 'cries.legacy']

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Columns: 213 entries, id to cries.legacy
dtypes: bool(1), int64(5), object(15), str(192)
memory usage: 1.8+ KB

In [5]:
df[['name', 'height', 'weight', 'base_experience', 'id', 'order']]

      name  height  weight  base_experience  id  order
0  pikachu       4      60              112  25     35

In [ ]:
respone = requests.get('https://pokeapi.co/api/v2/pokemon/pikachu')

In [7]:
response.json()

{'id': 25,
 'name': 'pikachu',
 'base_experience': 112,
 'height': 4,
 'is_default': True,
 'order': 35,
 'weight': 60,
 'abilities': [{'is_hidden': False,
   'slot': 1,
   'ability': {'name': 'static',
    'url': 'https://pokeapi.co/api/v2/ability/9/'}},
  {'is_hidden': True,
   'slot': 3,
   'ability': {'name': 'lightning-rod',
    'url': 'https://pokeapi.co/api/v2/ability/31/'}}],
 'past_abilities': [{'generation': {'name': 'generation-iv',
    'url': 'https://pokeapi.co/api/v2/generation/4/'},
   'abilities': [{'is_hidden': True, 'slot': 3, 'ability': None}]}],
 'forms': [{'name': 'pikachu',
   'url': 'https://pokeapi.co/api/v2/pokemon-form/25/'}],
 'game_indices': [{'game_index': 84,
   'version': {'name': 'red', 'url': 'https://pokeapi.co/api/v2/version/1/'}},
  {'game_index': 84,
   'version': {'name': 'blue', 'url': 'https://pokeapi.co/api/v2/version/2/'}},
  {'game_index': 84,
   'version': {'name': 'yellow',
    'url': 'https://pokeapi.co/api/v2/version/3/'}},
  {'game_index': 25,
   'version': {'name': 'gold', 'url': 'https://pokeapi.co/api/v2/version/4/'}},
  {'game_index': 25,
   'version': {'name': 'silver',
    'url': 'https://pokeapi.co/api/v2/version/5/'}},
  {'game_index': 25,
   'version': {'name': 'crystal',
    'url': 'https://pokeapi.co/api/v2/version/6/'}},
  {'game_index': 25,
   'version': {'name': 'ruby', 'url': 'https://pokeapi.co/api/v2/version/7/'}},
  {'game_index': 25,
   'version': {'name': 'sapphire',
    'url': 'https://pokeapi.co/api/v2/version/8/'}},
  {'game_index': 25,
   'version': {'name': 'emerald',
    'url': 'https://pokeapi.co/api/v2/version/9/'}},
  {'game_index': 25,
   'version': {'name': 'firered',
    'url': 'https://pokeapi.co/api/v2/version/10/'}},
  {'game_index': 25,
   'version': {'name': 'leafgreen',
    'url': 'https://pokeapi.co/api/v2/version/11/'}},
  {'game_index': 25,
   'version': {'name': 'diamond',
    'url': 'https://pokeapi.co/api/v2/version/12/'}},
  {'game_index': 25,
   'version': {'name': 'pearl',
    'url': 'https://pokeapi.co/api/v2/version/13/'}},
  {'game_index': 25,
   'version': {'name': 'platinum',
    'url': 'https://pokeapi.co/api/v2/version/14/'}},
  {'game_index': 25,
   'version': {'name': 'heartgold',
    'url': 'https://pokeapi.co/api/v2/version/15/'}},
  {'game_index': 25,
   'version': {'name': 'soulsilver',
    'url': 'https://pokeapi.co/api/v2/version/16/'}},
  {'game_index': 25,
   'version': {'name': 'black',
    'url': 'https://pokeapi.co/api/v2/version/17/'}},
  {'game_index': 25,
   'version': {'name': 'white',
    'url': 'https://pokeapi.co/api/v2/version/18/'}},
  {'game_index': 25,
   'version': {'name': 'black-2',
    'url': 'https://pokeapi.co/api/v2/version/21/'}},
  {'game_index': 25,
   'version': {'name': 'white-2',
    'url': 'https://pokeapi.co/api/v2/version/22/'}},
  {'game_index': 25,
   'version': {'name': 'x', 'url': 'https://pokeapi.co/api/v2/version/23/'}},
  {'game_index': 25,
   'version': {'name': 'y', 'url': 'https://pokeapi.co/api/v2/version/24/'}},
  {'game_index': 25,
   'version': {'name': 'omega-ruby',
    'url': 'https://pokeapi.co/api/v2/version/25/'}},
  {'game_index': 25,
   'version': {'name': 'alpha-sapphire',
    'url': 'https://pokeapi.co/api/v2/version/26/'}},
  {'game_index': 25,
   'version': {'name': 'sun', 'url': 'https://pokeapi.co/api/v2/version/27/'}},
  {'game_index': 25,
   'version': {'name': 'moon',
    'url': 'https://pokeapi.co/api/v2/version/28/'}},
  {'game_index': 25,
   'version': {'name': 'ultra-sun',
    'url': 'https://pokeapi.co/api/v2/version/29/'}},
  {'game_index': 25,
   'version': {'name': 'ultra-moon',
    'url': 'https://pokeapi.co/api/v2/version/30/'}},
  {'game_index': 25,
   'version': {'name': 'lets-go-pikachu',
    'url': 'https://pokeapi.co/api/v2/version/31/'}},
  {'game_index': 25,
   'version': {'name': 'lets-go-eevee',
    'url': 'https://pokeapi.co/api/v2/version/32/'}},
  {'game_index': 25,
   'version': {'name': 'sword',
    'url': 'https://pokeapi.co/api/v2/version/33/'}},
  {'game_index': 25,
   'version': {'name': 'shield',
    'url': 'https://pokeapi.co/api/v2/version/34/'}},
  {'game_index': 25,
   'version': {'name': 'the-isle-of-armor-sword',
    'url': 'https://pokeapi.co/api/v2/version/35/'}},
  {'game_index': 25,
   'version': {'name': 'the-crown-tundra-sword',
    'url': 'https://pokeapi.co/api/v2/version/36/'}},
  {'game_index': 25,
   'version': {'name': 'brilliant-diamond',
    'url': 'https://pokeapi.co/api/v2/version/37/'}},
  {'game_index': 25,
   'version': {'name': 'shining-pearl',
    'url': 'https://pokeapi.co/api/v2/version/38/'}},
  {'game_index': 25,
   'version': {'name': 'legends-arceus',
    'url': 'https://pokeapi.co/api/v2/version/39/'}},
  {'game_index': 25,
   'version': {'name': 'scarlet',
    'url': 'https://pokeapi.co/api/v2/version/40/'}},
  {'game_index': 25,
   'version': {'name': 'violet',
    'url': 'https://pokeapi.co/api/v2/version/41/'}},
  {'game_index': 25,
   'version': {'name': 'the-teal-mask-scarlet',
    'url': 'https://pokeapi.co/api/v2/version/42/'}},
  {'game_index': 25,
   'version': {'name': 'the-indigo-disk-scarlet',
    'url': 'https://pokeapi.co/api/v2/version/43/'}},
  {'game_index': 84,
   'version': {'name': 'red-japan',
    'url': 'https://pokeapi.co/api/v2/version/44/'}},
  {'game_index': 84,
   'version': {'name': 'green-japan',
    'url': 'https://pokeapi.co/api/v2/version/45/'}},
  {'game_index': 84,
   'version': {'name': 'blue-japan',
    'url': 'https://pokeapi.co/api/v2/version/46/'}},
  {'game_index': 25,
   'version': {'name': 'legends-za',
    'url': 'https://pokeapi.co/api/v2/version/47/'}},
  {'game_index': 25,
   'version': {'name': 'mega-dimension',
    'url': 'https://pokeapi.co/api/v2/version/48/'}}],
 'held_items': [{'item': {'name': 'oran-berry',
    'url': 'https://pokeapi.co/api/v2/item/132/'},
   'version_details': [{'rarity': 50,
     'version': {'name': 'ruby',
      'url': 'https://pokeapi.co/api/v2/version/7/'}},
    {'rarity': 50,
     'version': {'name': 'sapphire',
      'url': 'https://pokeapi.co/api/v2/version/8/'}},
    {'rarity': 50,
     'version': {'name': 'emerald',
      'url': 'https://pokeapi.co/api/v2/version/9/'}},
    {'rarity': 50,
     'version': {'name': 'diamond',
      'url': 'https://pokeapi.co/api/v2/version/12/'}},
    {'rarity': 50,
     'version': {'name': 'pearl',
      'url': 'https://pokeapi.co/api/v2/version/13/'}},
    {'rarity': 50,
     'version': {'name': 'platinum',
      'url': 'https://pokeapi.co/api/v2/version/14/'}},
    {'rarity': 50,
     'version': {'name': 'heartgold',
      'url': 'https://pokeapi.co/api/v2/version/15/'}},
    {'rarity': 50,
     'version': {'name': 'soulsilver',
      'url': 'https://pokeapi.co/api/v2/version/16/'}},
    {'rarity': 50,
     'version': {'name': 'black',
      'url': 'https://pokeapi.co/api/v2/version/17/'}},
    {'rarity': 50,
     'version': {'name': 'white',
      'url': 'https://pokeapi.co/api/v2/version/18/'}}]},
  {'item': {'name': 'light-ball',
    'url': 'https://pokeapi.co/api/v2/item/213/'},
   'version_details': [{'rarity': 5,
     'version': {'name': 'ruby',
      'url': 'https://pokeapi.co/api/v2/version/7/'}},
    {'rarity': 5,
     'version': {'name': 'sapphire',
      'url': 'https://pokeapi.co/api/v2/version/8/'}},
    {'rarity': 5,
     'version': {'name': 'emerald',
      'url': 'https://pokeapi.co/api/v2/version/9/'}},
    {'rarity': 5,
     'version': {'name': 'diamond',
      'url': 'https://pokeapi.co/api/v2/version/12/'}},
    {'rarity': 5,
     'version': {'name': 'pearl',
      'url': 'https://pokeapi.co/api/v2/version/13/'}},
    {'rarity': 5,
     'version': {'name': 'platinum',
      'url': 'https://pokeapi.co/api/v2/version/14/'}},
    {'rarity': 5,
     'version': {'name': 'heartgold',
      'url': 'https://pokeapi.co/api/v2/version/15/'}},
    {'rarity': 5,
     'version': {'name': 'soulsilver',
      'url': 'https://pokeapi.co/api/v2/version/16/'}},
    {'rarity': 1,
     'version': {'name': 'black',
      'url': 'https://pokeapi.co/api/v2/version/17/'}},
    {'rarity': 1,
     'version': {'name': 'white',
      'url': 'https://pokeapi.co/api/v2/version/18/'}},
    {'rarity': 5,
     'version': {'name': 'black-2',
      'url': 'https://pokeapi.co/api/v2/version/21/'}},
    {'rarity': 5,
     'version': {'name': 'white-2',
      'url': 'https://pokeapi.co/api/v2/version/22/'}},
    {'rarity': 5,
     'version': {'name': 'x', 'url': 'https://pokeapi.co/api/v2/version/23/'}},
    {'rarity': 5,
     'version': {'name': 'y', 'url': 'https://pokeapi.co/api/v2/version/24/'}},
    {'rarity': 5,
     'version': {'name': 'omega-ruby',
      'url': 'https://pokeapi.co/api/v2/version/25/'}},
    {'rarity': 5,
     'version': {'name': 'alpha-sapphire',
      'url': 'https://pokeapi.co/api/v2/version/26/'}},
    {'rarity': 5,
     'version': {'name': 'sun',
      'url': 'https://pokeapi.co/api/v2/version/27/'}},
    {'rarity': 5,
     'version': {'name': 'moon',
      'url': 'https://pokeapi.co/api/v2/version/28/'}},
    {'rarity': 5,
     'version': {'name': 'ultra-sun',
      'url': 'https://pokeapi.co/api/v2/version/29/'}},
    {'rarity': 5,
     'version': {'name': 'ultra-moon',
      'url': 'https://pokeapi.co/api/v2/version/30/'}}]}],
 'location_area_encounters': 'https://pokeapi.co/api/v2/pokemon/25/encounters',
 'moves': [{'move': {'name': 'mega-punch',
    'url': 'https://pokeapi.co/api/v2/move/5/'},
   'version_group_details': [{'level_learned_at': 0,
     'version_group': {'name': 'red-blue',
      'url': 'https://pokeapi.co/api/v2/version-group/1/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'yellow',
      'url': 'https://pokeapi.co/api/v2/version-group/2/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'emerald',
      'url': 'https://pokeapi.co/api/v2/version-group/6/'},
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'firered-leafgreen',
      'url': 'https://pokeapi.co/api/v2/version-group/7/'},
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'sword-shield',
      'url': 'https://pokeapi.co/api/v2/version-group/20/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'red-green-japan',
      'url': 'https://pokeapi.co/api/v2/version-group/28/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'blue-japan',
      'url': 'https://pokeapi.co/api/v2/version-group/29/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None}]},
  {'move': {'name': 'pay-day', 'url': 'https://pokeapi.co/api/v2/move/6/'},
   'version_group_details': [{'level_learned_at': 0,
     'version_group': {'name': 'red-blue',
      'url': 'https://pokeapi.co/api/v2/version-group/1/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'yellow',
      'url': 'https://pokeapi.co/api/v2/version-group/2/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'lets-go-pikachu-lets-go-eevee',
      'url': 'https://pokeapi.co/api/v2/version-group/19/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'sword-shield',
      'url': 'https://pokeapi.co/api/v2/version-group/20/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'red-green-japan',
      'url': 'https://pokeapi.co/api/v2/version-group/28/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'blue-japan',
      'url': 'https://pokeapi.co/api/v2/version-group/29/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None}]},
  {'move': {'name': 'thunder-punch',
    'url': 'https://pokeapi.co/api/v2/move/9/'},
   'version_group_details': [{'level_learned_at': 0,
     'version_group': {'name': 'gold-silver',
      'url': 'https://pokeapi.co/api/v2/version-group/3/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'crystal',
      'url': 'https://pokeapi.co/api/v2/version-group/4/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'emerald',
      'url': 'https://pokeapi.co/api/v2/version-group/6/'},
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'platinum',
      'url': 'https://pokeapi.co/api/v2/version-group/9/'},
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'heartgold-soulsilver',
      'url': 'https://pokeapi.co/api/v2/version-group/10/'},
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'black-2-white-2',
      'url': 'https://pokeapi.co/api/v2/version-group/14/'},
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'omega-ruby-alpha-sapphire',
      'url': 'https://pokeapi.co/api/v2/version-group/16/'},
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'ultra-sun-ultra-moon',
      'url': 'https://pokeapi.co/api/v2/version-group/18/'},
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'lets-go-pikachu-lets-go-eevee',
      'url': 'https://pokeapi.co/api/v2/version-group/19/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'sword-shield',
      'url': 'https://pokeapi.co/api/v2/version-group/20/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'scarlet-violet',
      'url': 'https://pokeapi.co/api/v2/version-group/25/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'champions',
      'url': 'https://pokeapi.co/api/v2/version-group/32/'},
     'move_learn_method': {'name': 'train',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/12/'},
     'order': None}]},
  {'move': {'name': 'slam', 'url': 'https://pokeapi.co/api/v2/move/21/'},
   'version_group_details': [{'level_learned_at': 20,
     'version_group': {'name': 'yellow',
      'url': 'https://pokeapi.co/api/v2/version-group/2/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 20,
     'version_group': {'name': 'gold-silver',
      'url': 'https://pokeapi.co/api/v2/version-group/3/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 20,
     'version_group': {'name': 'crystal',
      'url': 'https://pokeapi.co/api/v2/version-group/4/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 20,
     'version_group': {'name': 'ruby-sapphire',
      'url': 'https://pokeapi.co/api/v2/version-group/5/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 20,
     'version_group': {'name': 'emerald',
      'url': 'https://pokeapi.co/api/v2/version-group/6/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 20,
     'version_group': {'name': 'firered-leafgreen',
      'url': 'https://pokeapi.co/api/v2/version-group/7/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 21,
     'version_group': {'name': 'diamond-pearl',
      'url': 'https://pokeapi.co/api/v2/version-group/8/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 21,
     'version_group': {'name': 'platinum',
      'url': 'https://pokeapi.co/api/v2/version-group/9/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 21,
     'version_group': {'name': 'heartgold-soulsilver',
      'url': 'https://pokeapi.co/api/v2/version-group/10/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 26,
     'version_group': {'name': 'black-white',
      'url': 'https://pokeapi.co/api/v2/version-group/11/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 20,
     'version_group': {'name': 'colosseum',
      'url': 'https://pokeapi.co/api/v2/version-group/12/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 20,
     'version_group': {'name': 'xd',
      'url': 'https://pokeapi.co/api/v2/version-group/13/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 26,
     'version_group': {'name': 'black-2-white-2',
      'url': 'https://pokeapi.co/api/v2/version-group/14/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 26,
     'version_group': {'name': 'x-y',

In [8]:
data.keys()

dict_keys(['id', 'name', 'base_experience', 'height', 'is_default', 'order', 'weight', 'abilities', 'past_abilities', 'forms', 'game_indices', 'held_items', 'location_area_encounters', 'moves', 'species', 'sprites', 'cries', 'stats', 'past_stats', 'types', 'past_types'])

In [9]:
print("Name:", data['name'])
print("Height:", data['height'])
print("Weight:", data['weight'])
print("Abilities:", data['abilities'])
print("Types:", data['types'])
print("Stats:", data['stats'])

Name: pikachu
Height: 4
Weight: 60
Abilities: [{'is_hidden': False, 'slot': 1, 'ability': {'name': 'static', 'url': 'https://pokeapi.co/api/v2/ability/9/'}}, {'is_hidden': True, 'slot': 3, 'ability': {'name': 'lightning-rod', 'url': 'https://pokeapi.co/api/v2/ability/31/'}}]
Types: [{'slot': 1, 'type': {'name': 'electric', 'url': 'https://pokeapi.co/api/v2/type/13/'}}]
Stats: [{'base_stat': 35, 'effort': 0, 'stat': {'name': 'hp', 'url': 'https://pokeapi.co/api/v2/stat/1/'}}, {'base_stat': 55, 'effort': 0, 'stat': {'name': 'attack', 'url': 'https://pokeapi.co/api/v2/stat/2/'}}, {'base_stat': 40, 'effort': 0, 'stat': {'name': 'defense', 'url': 'https://pokeapi.co/api/v2/stat/3/'}}, {'base_stat': 50, 'effort': 0, 'stat': {'name': 'special-attack', 'url': 'https://pokeapi.co/api/v2/stat/4/'}}, {'base_stat': 50, 'effort': 0, 'stat': {'name': 'special-defense', 'url': 'https://pokeapi.co/api/v2/stat/5/'}}, {'base_stat': 90, 'effort': 2, 'stat': {'name': 'speed', 'url': 'https://pokeapi.co/api/v2/stat/6/'}}]

In [10]:
pd.json_normalize(data)
df.head()

,id,name,base_experience,height,is_default,order,weight,abilities,past_abilities,forms,...,sprites.back_shiny,sprites.back_female,sprites.front_shiny,sprites.back_default,sprites.front_female,sprites.front_default,sprites.back_shiny_female,sprites.front_shiny_female,cries.latest,cries.legacy
0,25,pikachu,112,4,True,35,60,"[{'is_hidden': False, 'slot': 1, 'ability': {'...","[{'generation': {'name': 'generation-iv', 'url...","[{'name': 'pikachu', 'url': 'https://pokeapi.c...",...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/crie...,https://raw.githubusercontent.com/PokeAPI/crie...

In [13]:
df.shape

(1, 213)

In [14]:
df.columns.tolist()

['id',
 'name',
 'base_experience',
 'height',
 'is_default',
 'order',
 'weight',
 'abilities',
 'past_abilities',
 'forms',
 'game_indices',
 'held_items',
 'location_area_encounters',
 'moves',
 'stats',
 'past_stats',
 'types',
 'past_types',
 'species.name',
 'species.url',
 'sprites.other.home.front_shiny',
 'sprites.other.home.front_female',
 'sprites.other.home.front_default',
 'sprites.other.home.front_shiny_female',
 'sprites.other.showdown.back_shiny',
 'sprites.other.showdown.back_female',
 'sprites.other.showdown.front_shiny',
 'sprites.other.showdown.back_default',
 'sprites.other.showdown.front_female',
 'sprites.other.showdown.front_default',
 'sprites.other.showdown.back_shiny_female',
 'sprites.other.showdown.front_shiny_female',
 'sprites.other.dream_world.front_female',
 'sprites.other.dream_world.front_default',
 'sprites.other.official-artwork.versions.generation-i.red-and-blue.front_default',
 'sprites.other.official-artwork.versions.generation-i.red-and-green.front_default',
 'sprites.other.official-artwork.versions.generation-ii.gold-and-silver.front_default',
 'sprites.other.official-artwork.front_shiny',
 'sprites.other.official-artwork.front_default',
 'sprites.versions.generation-i.yellow.back_gbc',
 'sprites.versions.generation-i.yellow.back_gray',
 'sprites.versions.generation-i.yellow.front_gbc',
 'sprites.versions.generation-i.yellow.front_gray',
 'sprites.versions.generation-i.yellow.back_default',
 'sprites.versions.generation-i.yellow.front_default',
 'sprites.versions.generation-i.yellow.back_transparent',
 'sprites.versions.generation-i.yellow.front_transparent',
 'sprites.versions.generation-i.yellow.back_transparent_gray',
 'sprites.versions.generation-i.yellow.front_transparent_gray',
 'sprites.versions.generation-i.red-blue.back_gray',
 'sprites.versions.generation-i.red-blue.front_gray',
 'sprites.versions.generation-i.red-blue.back_default',
 'sprites.versions.generation-i.red-blue.front_default',
 'sprites.versions.generation-i.red-blue.back_transparent',
 'sprites.versions.generation-i.red-blue.front_transparent',
 'sprites.versions.generation-i.red-blue.back_transparent_gray',
 'sprites.versions.generation-i.red-blue.front_transparent_gray',
 'sprites.versions.generation-i.red-green-japan.back_gray',
 'sprites.versions.generation-i.red-green-japan.front_gray',
 'sprites.versions.generation-i.red-green-japan.back_default',
 'sprites.versions.generation-i.red-green-japan.front_default',
 'sprites.versions.generation-v.icons.animated.front_default',
 'sprites.versions.generation-v.icons.front_default',
 'sprites.versions.generation-v.black-white.animated.back_shiny',
 'sprites.versions.generation-v.black-white.animated.back_female',
 'sprites.versions.generation-v.black-white.animated.front_shiny',
 'sprites.versions.generation-v.black-white.animated.back_default',
 'sprites.versions.generation-v.black-white.animated.front_female',
 'sprites.versions.generation-v.black-white.animated.front_default',
 'sprites.versions.generation-v.black-white.animated.back_shiny_female',
 'sprites.versions.generation-v.black-white.animated.front_shiny_female',
 'sprites.versions.generation-v.black-white.back_shiny',
 'sprites.versions.generation-v.black-white.back_female',
 'sprites.versions.generation-v.black-white.front_shiny',
 'sprites.versions.generation-v.black-white.back_default',
 'sprites.versions.generation-v.black-white.front_female',
 'sprites.versions.generation-v.black-white.front_default',
 'sprites.versions.generation-v.black-white.back_shiny_female',
 'sprites.versions.generation-v.black-white.front_shiny_female',
 'sprites.versions.generation-ii.gold.back_shiny',
 'sprites.versions.generation-ii.gold.front_shiny',
 'sprites.versions.generation-ii.gold.back_default',
 'sprites.versions.generation-ii.gold.front_default',
 'sprites.versions.generation-ii.gold.back_transparent',
 'sprites.versions.generation-ii.gold.front_transparent',
 'sprites.versions.generation-ii.gold.back_shiny_transparent',
 'sprites.versions.generation-ii.gold.front_shiny_transparent',
 'sprites.versions.generation-ii.silver.back_shiny',
 'sprites.versions.generation-ii.silver.front_shiny',
 'sprites.versions.generation-ii.silver.back_default',
 'sprites.versions.generation-ii.silver.front_default',
 'sprites.versions.generation-ii.silver.back_transparent',
 'sprites.versions.generation-ii.silver.front_transparent',
 'sprites.versions.generation-ii.silver.back_shiny_transparent',
 'sprites.versions.generation-ii.silver.front_shiny_transparent',
 'sprites.versions.generation-ii.crystal.animated.front_shiny',
 'sprites.versions.generation-ii.crystal.animated.front_default',
 'sprites.versions.generation-ii.crystal.back_shiny',
 'sprites.versions.generation-ii.crystal.front_shiny',
 'sprites.versions.generation-ii.crystal.back_default',
 'sprites.versions.generation-ii.crystal.front_default',
 'sprites.versions.generation-ii.crystal.back_transparent',
 'sprites.versions.generation-ii.crystal.front_transparent',
 'sprites.versions.generation-ii.crystal.back_shiny_transparent',
 'sprites.versions.generation-ii.crystal.front_shiny_transparent',
 'sprites.versions.generation-iv.icons.front_default',
 'sprites.versions.generation-iv.platinum.animated.front_shiny',
 'sprites.versions.generation-iv.platinum.animated.front_female',
 'sprites.versions.generation-iv.platinum.animated.front_default',
 'sprites.versions.generation-iv.platinum.animated.front_shiny_female',
 'sprites.versions.generation-iv.platinum.back_shiny',
 'sprites.versions.generation-iv.platinum.back_female',
 'sprites.versions.generation-iv.platinum.front_shiny',
 'sprites.versions.generation-iv.platinum.back_default',
 'sprites.versions.generation-iv.platinum.front_female',
 'sprites.versions.generation-iv.platinum.front_default',
 'sprites.versions.generation-iv.platinum.back_shiny_female',
 'sprites.versions.generation-iv.platinum.front_shiny_female',
 'sprites.versions.generation-iv.diamond-pearl.animated.front_shiny',
 'sprites.versions.generation-iv.diamond-pearl.animated.front_female',
 'sprites.versions.generation-iv.diamond-pearl.animated.front_default',
 'sprites.versions.generation-iv.diamond-pearl.animated.front_shiny_female',
 'sprites.versions.generation-iv.diamond-pearl.back_shiny',
 'sprites.versions.generation-iv.diamond-pearl.back_female',
 'sprites.versions.generation-iv.diamond-pearl.front_shiny',
 'sprites.versions.generation-iv.diamond-pearl.back_default',
 'sprites.versions.generation-iv.diamond-pearl.front_female',
 'sprites.versions.generation-iv.diamond-pearl.front_default',
 'sprites.versions.generation-iv.diamond-pearl.back_shiny_female',
 'sprites.versions.generation-iv.diamond-pearl.front_shiny_female',
 'sprites.versions.generation-iv.heartgold-soulsilver.animated.front_shiny',
 'sprites.versions.generation-iv.heartgold-soulsilver.animated.front_female',
 'sprites.versions.generation-iv.heartgold-soulsilver.animated.front_default',
 'sprites.versions.generation-iv.heartgold-soulsilver.animated.front_shiny_female',
 'sprites.versions.generation-iv.heartgold-soulsilver.back_shiny',
 'sprites.versions.generation-iv.heartgold-soulsilver.back_female',
 'sprites.versions.generation-iv.heartgold-soulsilver.front_shiny',
 'sprites.versions.generation-iv.heartgold-soulsilver.back_default',
 'sprites.versions.generation-iv.heartgold-soulsilver.front_female',
 'sprites.versions.generation-iv.heartgold-soulsilver.front_default',
 'sprites.versions.generation-iv.heartgold-soulsilver.back_shiny_female',
 'sprites.versions.generation-iv.heartgold-soulsilver.front_shiny_female',
 'sprites.versions.generation-ix.champions.front_shiny',
 'sprites.versions.generation-ix.champions.front_default',
 'sprites.versions.generation-ix.scarlet-violet.front_female',
 'sprites.versions.generation-ix.scarlet-violet.front_default',
 'sprites.versions.generation-vi.x-y.back_shiny',
 'sprites.versions.generation-vi.x-y.back_female',
 'sprites.versions.generation-vi.x-y.front_shiny',
 'sprites.versions.generation-vi.x-y.back_default',
 'sprites.versions.generation-vi.x-y.front_female',
 'sprites.versions.generation-vi.x-y.front_default',
 'sprites.versions.generation-vi.x-y.back_shiny_female',
 'sprites.versions.generation-vi.x-y.front_shiny_female',
 'sprites.versions.generation-vi.icons.front_female',
 'sprites.versions.generation-vi.icons.front_default',
 'sprites.versions.generation-vi.omegaruby-alphasapphire.back_shiny',
 'sprites.versions.generation-vi.omegaruby-alphasapphire.back_female',
 'sprites.versions.generation-vi.omegaruby-alphasapphire.front_shiny',
 'sprites.versions.generation-vi.omegaruby-alphasapphire.back_default',
 'sprites.versions.generation-vi.omegaruby-alphasapphire.front_female',
 'sprites.versions.generation-vi.omegaruby-alphasapphire.front_default',
 'sprites.versions.generation-vi.omegaruby-alphasapphire.back_shiny_female',
 'sprites.versions.generation-vi.omegaruby-alphasapphire.front_shiny_female',
 'sprites.versions.generation-iii.icons.front_default',
 'sprites.versions.generation-iii.emerald.animated.back_shiny',
 'sprites.versions.generation-iii.emerald.animated.front_shiny',
 'sprites.versions.generation-iii.emerald.animated.back_default',
 'sprites.versions.generation-iii.emerald.animated.front_default',
 'sprites.versions.generation-iii.emerald.back_shiny',
 'sprites.versions.generation-iii.emerald.front_shiny',
 'sprites.versions.generation-iii.emerald.back_default',
 'sprites.versions.generation-iii.emerald.front_default',
 'sprites.versions.generation-iii.ruby-sapphire.back_shiny',
 'sprites.versions.generation-iii.ruby-sapphire.front_shiny',
 'sprites.versions.generation-iii.ruby-sapphire.back_default',
 'sprites.versions.generation-iii.ruby-sapphire.front_default',
 'sprites.versions.generation-iii.firered-leafgreen.back_shiny',
 'sprites.versions.generation-iii.firered-leafgreen.front_shiny',
 'sprites.versions.generation-iii.firered-leafgreen.back_default',
 'sprites.versions.generation-iii.firered-leafgreen.front_default',
 'sprites.versions.generation-vii.icons.front_female',
 'sprites.versions.generation-vii.icons.front_default',
 'sprites.versions.generation-vii.ultra-sun-ultra-moon.back_shiny',
 'sprites.versions.generation-vii.ultra-sun-ultra-moon.back_female',
 'sprites.versions.generation-vii.ultra-sun-ultra-moon.front_shiny',
 'sprites.versions.generation-vii.ultra-sun-ultra-moon.back_default',
 'sprites.versions.generation-vii.ultra-sun-ultra-moon.front_female',
 'sprites.versions.generation-vii.ultra-sun-ultra-moon.front_default',
 'sprites.versions.generation-vii.ultra-sun-ultra-moon.back_shiny_female',
 'sprites.versions.generation-vii.ultra-sun-ultra-moon.front_shiny_female',
 'sprites.versions.generation-vii.lets-go-pikachu-lets-go-eevee.icons.front_default',
 'sprites.versions.generation-vii.lets-go-pikachu-lets-go-eevee.back_shiny',
 'sprites.versions.generation-vii.lets-go-pikachu-lets-go-eevee.back_female',
 'sprites.versions.generation-vii.lets-go-pikachu-lets-go-eevee.front_shiny',
 'sprites.versions.generation-vii.lets-go-pikachu-lets-go-eevee.back_default',
 'sprites.versions.generation-vii.lets-go-pikachu-lets-go-eevee.front_female',
 'sprites.versions.generation-vii.lets-go-pikachu-lets-go-eevee.front_default',
 'sprites.versions.generation-vii.lets-go-pikachu-lets-go-eevee.back_shiny_female',
 'sprites.versions.generation-vii.lets-go-pikachu-lets-go-eevee.front_shiny_female',
 'sprites.versions.generation-viii.icons.front_female',
 'sprites.versions.generation-viii.icons.front_default',
 'sprites.versions.generation-viii.brilliant-diamond-shining-pearl.front_default',
 'sprites.back_shiny',
 'sprites.back_female',
 'sprites.front_shiny',
 'sprites.back_default',
 'sprites.front_female',
 'sprites.front_default',
 'sprites.back_shiny_female',
 'sprites.front_shiny_female',
 'cries.latest',
 'cries.legacy']

In [15]:
df[['name', 'height', 'weight', 'base_experience', 'id', 'order']]

      name  height  weight  base_experience  id  order
0  pikachu       4      60              112  25     35

In [16]:
# Abilities ko readable banao
df['abilities_clean'] = df['abilities'].apply(
    lambda x: ", ".join([a['ability']['name'] for a in x])
)

# Types ko readable banao
df['types_clean'] = df['types'].apply(
    lambda x: ", ".join([t['type']['name'] for t in x])
)

# Stats ko readable banao
df['stats_clean'] = df['stats'].apply(
    lambda x: ", ".join([f"{s['stat']['name']}:{s['base_stat']}" for s in x])
)

df[['name', 'height', 'weight', 'base_experience', 'abilities_clean', 'types_clean', 'stats_clean']]

,name,height,weight,base_experience,abilities_clean,types_clean,stats_clean
0,pikachu,4,60,112,"static, lightning-rod",electric,"hp:35, attack:55, defense:40, special-attack:5..."

In [17]:
clean_df = df[['name', 'height', 'weight', 'base_experience', 'abilities_clean', 'types_clean', 'stats_clean']]
clean_df.to_csv("pokemon_clean.csv", index=False)
print("Saved!")

Saved!

In [18]:
clean_df

,name,height,weight,base_experience,abilities_clean,types_clean,stats_clean
0,pikachu,4,60,112,"static, lightning-rod",electric,"hp:35, attack:55, defense:40, special-attack:5..."

## LOOP DATA FETCHING

In [19]:
import requests
import pandas as pd

all_pokemon = []   # khaali list — har pokemon ka data isme jayega

for i in range(1, 51):   # 1 se 10 pokemon (baad mein 51 kar sakte ho)
    url = f"https://pokeapi.co/api/v2/pokemon/{i}"
    response = requests.get(url)
    r = response.json()
    
    all_pokemon.append({
        'id': r['id'],
        'name': r['name'],
        'height': r['height'],
        'weight': r['weight'],
        'base_experience': r['base_experience'],
        'types': ", ".join([t['type']['name'] for t in r['types']]),
        'abilities': ", ".join([a['ability']['name'] for a in r['abilities']]),
    })

df_all = pd.DataFrame(all_pokemon)
df_all

,id,name,height,weight,base_experience,types,abilities
0,1,bulbasaur,7,69,64,"grass, poison","overgrow, chlorophyll"
1,2,ivysaur,10,130,142,"grass, poison","overgrow, chlorophyll"
2,3,venusaur,20,1000,236,"grass, poison","overgrow, chlorophyll"
3,4,charmander,6,85,62,fire,"blaze, solar-power"
4,5,charmeleon,11,190,142,fire,"blaze, solar-power"
5,6,charizard,17,905,240,"fire, flying","blaze, solar-power"
6,7,squirtle,5,90,63,water,"torrent, rain-dish"
7,8,wartortle,10,225,142,water,"torrent, rain-dish"
8,9,blastoise,16,855,239,water,"torrent, rain-dish"
9,10,caterpie,3,29,39,bug,"shield-dust, run-away"
10,11,metapod,7,99,72,bug,shed-skin
11,12,butterfree,11,320,178,"bug, flying","compound-eyes, tinted-lens"
12,13,weedle,3,32,39,"bug, poison","shield-dust, run-away"
13,14,kakuna,6,100,72,"bug, poison",shed-skin
14,15,beedrill,10,295,178,"bug, poison","swarm, sniper"
15,16,pidgey,3,18,50,"normal, flying","keen-eye, tangled-feet, big-pecks"
16,17,pidgeotto,11,300,122,"normal, flying","keen-eye, tangled-feet, big-pecks"
17,18,pidgeot,15,395,216,"normal, flying","keen-eye, tangled-feet, big-pecks"
18,19,rattata,3,35,51,normal,"run-away, guts, hustle"
19,20,raticate,7,185,145,normal,"run-away, guts, hustle"
20,21,spearow,3,20,52,"normal, flying","keen-eye, sniper"
21,22,fearow,12,380,155,"normal, flying","keen-eye, sniper"
22,23,ekans,20,69,58,poison,"intimidate, shed-skin, unnerve"
23,24,arbok,35,650,157,poison,"intimidate, shed-skin, unnerve"
24,25,pikachu,4,60,112,electric,"static, lightning-rod"
25,26,raichu,8,300,218,electric,"static, lightning-rod"
26,27,sandshrew,6,120,60,ground,"sand-veil, sand-rush"
27,28,sandslash,10,295,158,ground,"sand-veil, sand-rush"
28,29,nidoran-f,4,70,55,poison,"poison-point, rivalry, hustle"
29,30,nidorina,8,200,128,poison,"poison-point, rivalry, hustle"
30,31,nidoqueen,13,600,227,"poison, ground","poison-point, rivalry, sheer-force"
31,32,nidoran-m,5,90,55,poison,"poison-point, rivalry, hustle"
32,33,nidorino,9,195,128,poison,"poison-point, rivalry, hustle"
33,34,nidoking,14,620,227,"poison, ground","poison-point, rivalry, sheer-force"
34,35,clefairy,6,75,113,fairy,"cute-charm, magic-guard, friend-guard"
35,36,clefable,13,400,217,fairy,"cute-charm, magic-guard, unaware"
36,37,vulpix,6,99,60,fire,"flash-fire, drought"
37,38,ninetales,11,199,177,fire,"flash-fire, drought"
38,39,jigglypuff,5,55,95,"normal, fairy","cute-charm, competitive, friend-guard"
39,40,wigglytuff,10,120,196,"normal, fairy","cute-charm, competitive, frisk"
40,41,zubat,8,75,49,"poison, flying","inner-focus, infiltrator"
41,42,golbat,16,550,159,"poison, flying","inner-focus, infiltrator"
42,43,oddish,5,54,64,"grass, poison","chlorophyll, run-away"
43,44,gloom,8,86,138,"grass, poison","chlorophyll, stench"
44,45,vileplume,12,186,221,"grass, poison","chlorophyll, effect-spore"
45,46,paras,3,54,57,"bug, grass","effect-spore, dry-skin, damp"
46,47,parasect,10,295,142,"bug, grass","effect-spore, dry-skin, damp"
47,48,venonat,10,300,61,"bug, poison","compound-eyes, tinted-lens, run-away"
48,49,venomoth,15,125,158,"bug, poison","shield-dust, tinted-lens, wonder-skin"
49,50,diglett,2,8,53,ground,"sand-veil, arena-trap, sand-force"

In [20]:
df_all.shape

(50, 7)

In [21]:
df_all.head()
df_all.info()
df_all.describe()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               50 non-null     int64
 1   name             50 non-null     str
 2   height           50 non-null     int64
 3   weight           50 non-null     int64
 4   base_experience  50 non-null     int64
 5   types            50 non-null     str
 6   abilities        50 non-null     str
dtypes: int64(4), str(3)
memory usage: 2.9 KB

             id     height       weight  base_experience
count  50.00000  50.000000    50.000000        50.000000
mean   25.50000   9.440000   234.140000       124.840000
std    14.57738   5.855958   239.438119        65.474519
min     1.00000   2.000000     8.000000        39.000000
25%    13.25000   5.250000    71.250000        60.250000
50%    25.50000   8.500000   127.500000       128.000000
75%    37.75000  11.750000   300.000000       172.500000
max    50.00000  35.000000  1000.000000       240.000000

In [22]:
df_all.to_csv("clean-pokemon2.csv", index=False)
print("Saved: clean-pokemon2.csv")

Saved: clean-pokemon2.csv

In [23]:
df_check = pd.read_csv("clean-pokemon2.csv")
df_check.head()

,id,name,height,weight,base_experience,types,abilities
0,1,bulbasaur,7,69,64,"grass, poison","overgrow, chlorophyll"
1,2,ivysaur,10,130,142,"grass, poison","overgrow, chlorophyll"
2,3,venusaur,20,1000,236,"grass, poison","overgrow, chlorophyll"
3,4,charmander,6,85,62,fire,"blaze, solar-power"
4,5,charmeleon,11,190,142,fire,"blaze, solar-power"